[php-74:worker]
command=/usr/bin/php /var/www/php-74/worker.php
process_name=%(program_name)s_%(process_num)02d
numprocs=2
directory=/var/www/php-74
stdout_logfile=/var/log/php-74/worker.php.log
autostart=true
autorestart=true
user=www-data
stopsignal=KILL